version: '3.3'

services:

  mq:
    image: uiobmi/localega-broker-public:latest
    ports:
      - "5671:5671"
      - "15671:15671"
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        window: 120s
    environment:
      - USER_NAME
      - "PASSWORD_HASH=${PASSWORD_HASH}"
      - "PRIVATE_CONNECTION=amqps://admin:guest@${PRIVATE_HOST}:5671/%2F?heartbeat=0\&connection_attempts=30\&retry_delay=10\&server_name_indication=privateMQ\&verify=verify_peer\&fail_if_no_peer_cert=true\&cacertfile=/etc/rabbitmq/CA.cert\&certfile=/etc/rabbitmq/ssl.cert\&keyfile=/etc/rabbitmq/ssl.key"
      - CEGA_CONNECTION
    configs:
      - source: mq.cert
        target: /etc/rabbitmq/ssl.cert
      - source: mq.key
        target: /etc/rabbitmq/ssl.key
      - source: CA.cert
        target: /etc/rabbitmq/CA.cert

configs:
  CA.cert:
    external: true
  mq.cert:
    external: true
  mq.key:
    external: true
