version: '3.3'

services:

  mq:
    image: uiobmi/localega-broker-private:uh
    ports:
      - "5671:5671"
      - "15671:15671"
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        window: 120s
    environment:
      - USER_NAME
      - PASSWORD_HASH
    configs:
      - source: mq.cert
        target: /etc/rabbitmq/ssl.cert
      - source: mq.key
        target: /etc/rabbitmq/ssl.key
      - source: CA.cert
        target: /etc/rabbitmq/CA.cert

configs:
  CA.cert:
    external: true
  mq.cert:
    external: true
  mq.key:
    external: true
