version: '3.3'

services:

  public-mq:
    image: uiobmi/localega-broker:public
    hostname: public-mq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - USER_NAME=admin
      - PASSWORD_HASH=4tHURqDiZzypw0NTvoHhpn8/MMgONWonWxgRZ4NXgR8nZRBz
      - PRIVATE_CONNECTION=amqp://admin:guest@private-mq:5672
      - CEGA_CONNECTION

  private-mq:
    image: uiobmi/localega-broker:private
    hostname: private-mq
    ports:
      - "15673:15672"
    environment:
      - USER_NAME=admin
      - PASSWORD_HASH=4tHURqDiZzypw0NTvoHhpn8/MMgONWonWxgRZ4NXgR8nZRBz
      - PUBLIC_CONNECTION=amqp://admin:guest@public-mq:5672
