version: '3.3'

services:

  mq:
    image: uiobmi/localega-broker
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - CEGA_CONNECTION
      - USER_NAME
      - PASSWORD_HASH
